---
# tasks file for wmi_exporter_installer

- name: Copy wmi_exporter.msi to Windows Servers
  win_copy:
    src: "{{ wmi_exporter_filename }}"
    dest: "{{ wmi_exporter_filepath }}"

- name: Install wmi_exporter for Windows Servers
  win_package:
    path: "{{ wmi_exporter_filepath }}{{ wmi_exporter_filename }}"
    arguments: "{{ wmi_exporter_install_args }}"
    state: present
